version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: api-db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - timeboost

networks:
  timeboost:
    driver: bridge
